version: "3.8"


services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    image: flask-demo:latest
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PASS=${REDIS_PASSWORD}
      # 这里给flask服务的容器内添加了REDIS_PASSWORD环境变量
      # 供python程序链接redis时使用
    networks:
      - backend
      - frontend

  redis-server:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    # 这里在启动redis命令上添加了REDIS_PASSWORD变量,
    # 使得redis需要使用设定的密码进行链接
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    depends_on:
      - flask
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./var/log/nginx:/var/log/nginx
        # 不要这个log的映射了,有点麻烦
    networks:
      - frontend

networks:
  backend:
  frontend:

# 上边在redis-server和flask两个service
# 中间都使用了REDIS_PASSWORD变量
# docker-compose可以通过环境变量文件来读取这个参数
# 默认的环境变量文件是.env
# 也可以通过 --env-file PATH 来手动指定环境变量文件