version: "3.8"

services: 
  flask-demo: 
    build:
      context: ./flask
      dockerfile: flask-demo.dockerfile
    image: flask-demo:latest
    environment:                
      - REDIS_HOST=redis-server
    networks:                   
      - demo-network
    ports:                      
      - 8080:5000
  redis-server:
    image: redis:latest
    networks:
     - demo-network
  buzy-box:
    image: busybox:latest
    networks:
      - demo-network
    command: 
      /bin/sh -c "while true; do sleep 3600; done"
networks:      
  demo-network: